### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by bearcott** [ashwinr/less-build#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [less-build](https://github.com/ashwinr/less-build) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809

TypeError: Cannot read property 'length' of undefined
  at Object.module.exports.LessBuild.buildLESS (/Users/bear/.atom/packages/less-build/lib/less-build.coffee:42:45)
  at Object.module.exports.LessBuild.build (/Users/bear/.atom/packages/less-build/lib/less-build.coffee:34:8)
  at /Users/bear/.atom/packages/less-build/lib/less-build.coffee:28:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1038:20)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1005:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:584:26)
  at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:547:18)
  at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:609:35)
  at atom-workspace.atom.commands.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:293:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -1:21.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:20.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:19.6.0 core:copy (atom-text-editor.editor.is-focused)
     -1:18 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -1:17.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -1:16.5.0 core:save (atom-text-editor.editor.mini.is-focused)
     -1:04.4.0 find-and-replace:show (div.settings-view.pane-item)
     -1:03.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:29.7.0 core:close (div.settings-view.pane-item)
     -0:27.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  4x -0:03.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
less-build, v0.1.0

# Dev
No dev packages
```

**Comment by kiran94** [comment]
+1

**Comment by linusrachlis** [comment]
I think this happened because I'm new to Atom and I don't know where to put the config mentioned in README.md, so there are no paths configured.

**Comment by cxwithyxy** [comment]
C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:825
error : Uncaught TypeError: Cannot read property 'length' of undefined

**Comment by dmitrii-esin** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Unknown Windows Version
**Thrown From**: [less-build](https://github.com/ashwinr/less-build) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:829

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.LessBuild.buildLESS (file:///C:/Users/dmitr/.atom/packages/less-build/lib/less-build.coffee:42:45)
    at Object.module.exports.LessBuild.build (file:///C:/Users/dmitr/.atom/packages/less-build/lib/less-build.coffee:34:8)
    at file:///C:/Users/dmitr/.atom/packages/less-build/lib/less-build.coffee:28:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1067:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1037:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\text-editor.js:602:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\workspace.js:648:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (C:\Users\dmitr\AppData\Local\atom\app-1.4.3\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:04.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "wrap-guide"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.28.21
atom-jade, v0.3.0
atom-less, v0.1.10
autocomplete-paths, v1.0.2
color-picker, v2.1.0
css-snippets, v0.9.0
emmet, v2.4.1
jQuery, v1.2.1
jquery-snippets, v11.0.0
language-SCSS, v0.4.0
less-build, v0.1.0
linter-jade, v0.3.2
minimap, v4.19.0
Remote-FTP, v0.7.15
seti-ui, v0.8.1
snippets-jade, v0.1.1
source-preview-jade, v0.1.1

# Dev
No dev packages
```

**Comment by ashwinr** [comment]
i'd gladly accept a PR here :)

**Comment by eupiteco** [comment]
Same problem here...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [less-build](https://github.com/ashwinr/less-build) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:1002

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.LessBuild.buildLESS (file:///C:/Users/Avell/.atom/packages/less-build/lib/less-build.coffee:42:45)
    at Object.module.exports.LessBuild.build (file:///C:/Users/Avell/.atom/packages/less-build/lib/less-build.coffee:34:8)
    at file:///C:/Users/Avell/.atom/packages/less-build/lib/less-build.coffee:28:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Avell\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
 10x -2:34.8.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -2:32.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:31 core:move-up (atom-text-editor.editor.is-focused)
 52x -2:31 core:move-right (atom-text-editor.editor.is-focused)
     -2:27.6.0 core:move-left (atom-text-editor.editor.is-focused)
 25x -2:27.3.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -2:25.6.0 core:move-left (atom-text-editor.editor.is-focused)
 44x -2:24.7.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:19.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:16.3.0 core:move-right (atom-text-editor.editor.is-focused)
  8x -2:15.5.0 core:select-right (atom-text-editor.editor.is-focused)
  9x -2:13.4.0 core:undo (atom-text-editor.editor.is-focused)
 10x -2:06.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:55.5.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
  2x -1:49.9.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -1:45.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

``` json
{}
```

### Installed Packages

``` coffee
# User
atom-less, v0.1.10
emmet, v2.4.3
less-build, v0.1.0
pigments, v0.29.3

# Dev
No dev packages
```

**Comment by misslou** [comment]
Uncaught TypeError: Cannot read property 'length' of undefined

C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:1026
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.LessBuild.buildLESS (file:///C:/Users/Administrator/.atom/packages/less-build/lib/less-build.coffee:42:45)
    at Object.module.exports.LessBuild.build (file:///C:/Users/Administrator/.atom/packages/less-build/lib/less-build.coffee:34:8)
    at file:///C:/Users/Administrator/.atom/packages/less-build/lib/less-build.coffee:28:8
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\node_modules\event-kit\lib\emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1156:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\text-editor.js:755:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:734:18)
    at Pane.saveItem (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:3:61)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\pane.js:717:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\workspace.js:699:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\register-default-commands.js:220:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.9.9\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by Brieg** [comment]
[Enter steps to reproduce:]

1. Install package
2. Go to .less file
3. Input one valid changes

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [less-build](https://github.com/ashwinr/less-build) package 0.1.0


### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\mbriegmann\AppData\Local\atom\app-1.17.2\resources\app\src\pane.js:1095

TypeError: Cannot read property 'length' of undefined
    at Object.buildLESS (/packages/less-build/lib/less-build.coffee:42:45)
    at Object.build (/packages/less-build/lib/less-build.coffee:34:8)
    at /packages/less-build/lib/less-build.coffee:28:8
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at TextBuffer.module.exports.TextBuffer.saveAs (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1142:1)
    at TextBuffer.module.exports.TextBuffer.save (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/text-buffer/lib/text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (~/AppData/Local/atom/app-1.17.2/resources/app/src/text-editor.js:925:1)
    at Pane.module.exports.Pane.saveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:780:1)
    at Pane.saveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:3:1)
    at Pane.module.exports.Pane.saveActiveItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/pane.js:763:1)
    at Workspace.saveActivePaneItem (~/AppData/Local/atom/app-1.17.2/resources/app/src/workspace.js:1498:1)
    at atom-workspace.core:save (~/AppData/Local/atom/app-1.17.2/resources/app/src/register-default-commands.js:236:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -4:34.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -2:23.3.0 settings-view:open (atom-pane.pane.active)
     -2:20.1.0 core:confirm (input.hidden-input)
 40x -1:07.3.0 core:page-up (input.hidden-input)
     -0:51.8.0 core:backspace (input.hidden-input)
     -0:51.3.0 intentions:highlight (input.hidden-input)
  2x -0:48.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-brackets-glow 0.4.0 
atom-typescript 11.0.3 
autocomplete-ionic2-framework 0.3.2 
busy-signal 1.4.0 
file-icons 2.1.3 
file-watcher 1.1.0 
go-to-file 0.2.0 
intentions 1.1.2 
jsformat 0.9.3 
less-autocompile 1.0.0 
less-build 0.1.0 
linter 2.1.4 
linter-ui-default 1.2.3 
php-cs-fixer 4.1.0 
```
